namespace Monify;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Generates the Monify attribute, used to denote when a type should serve as a wrapper for a single value.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AttributeGenerator
    : IIncrementalGenerator
{
    /// <summary>
    /// The source code that will be output by the generator.
    /// </summary>
    internal const string Content = $$"""
        #if NET8_0_OR_GREATER
        
        namespace Monify
        {
            using System;
            using System.Diagnostics.CodeAnalysis;
        
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
            internal sealed class {{Name}}Attribute<T>
                : Attribute
            {
            }
        }

        #endif
        """;

    /// <summary>
    /// The hint name used for the code generated by the generator.
    /// </summary>
    internal const string Hint = $"{Name}Attribute.g.cs";

    /// <summary>
    /// The name of the attribute (without the suffix).
    /// </summary>
    internal const string Name = "Monify";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(Generate);
    }

    private static void Generate(IncrementalGeneratorPostInitializationContext context)
    {
        var text = SourceText.From(Content, Encoding.UTF8);

        context.AddSource(Hint, text);
    }
}