namespace Monify.Snippets.Declarations.Records;

using Microsoft.CodeAnalysis.CSharp;
using static Monify.Snippets.Declarations.Attributes.Annotations;

internal static partial class Nested
{
    public static partial class InStruct
    {
        public static readonly Snippets NonNullable = new(
            [Generic, NonGeneric],
            Declarations.Main,
            [
                Expected.NonNullable.BinaryAdditionOperator,
                Expected.NonNullable.BinaryBitwiseAndOperator,
                Expected.NonNullable.BinaryBitwiseOrOperator,
                Expected.NonNullable.BinaryDivisionOperator,
                Expected.NonNullable.BinaryExclusiveOrOperator,
                Expected.NonNullable.BinaryGreaterThanOperator,
                Expected.NonNullable.BinaryGreaterThanOrEqualOperator,
                Expected.NonNullable.BinaryLeftShiftOperator,
                Expected.NonNullable.BinaryLessThanOperator,
                Expected.NonNullable.BinaryLessThanOrEqualOperator,
                Expected.NonNullable.BinaryModulusOperator,
                Expected.NonNullable.BinaryMultiplyOperator,
                Expected.NonNullable.BinaryRightShiftOperator,
                Expected.NonNullable.BinarySubtractionOperator,
                Expected.NonNullable.ConstructorForEncapsulatedValue,
                Expected.NonNullable.ConversionFromValue,
                Expected.NonNullable.ConversionToValue,
                Expected.NonNullable.EqualityOperatorForValue,
                Expected.NonNullable.EquatableForValue,
                Expected.NonNullable.EquatableToValue,
                Expected.NonNullable.FieldForEncapsulatedValue,
                Expected.NonNullable.ComparableInterface,
                Expected.NonNullable.ComparableGenericInterface,
                Expected.NonNullable.InequalityOperatorForValue,
                Expected.NonNullable.CompareToInt,
                Expected.NonNullable.CompareToObject,
                Expected.NonNullable.UnaryDecrementOperator,
                Expected.NonNullable.UnaryIncrementOperator,
                Expected.NonNullable.UnaryOnesComplementOperator,
                Expected.NonNullable.UnaryNegationOperator,
                Expected.NonNullable.UnaryPlusOperator,
            ],
            [
                new(Expected.NonNullable.ConstructorForEncapsulatedValue.Content, Extensions.HasConstructorForEncapsulatedValue),
                new(Expected.NonNullable.ConversionFromValue.Content, Extensions.HasConversionFrom),
                new(Expected.NonNullable.ConversionToValue.Content, Extensions.HasConversionTo),
                new(Expected.NonNullable.EqualityOperatorForValue.Content, Extensions.HasEqualityOperatorForValue),
                new(Expected.NonNullable.EquatableForValue.Content, Extensions.HasEquatableForValue),
                new(Expected.NonNullable.EquatableToValue.Content, Extensions.IsEquatableToValue),
                new(Expected.NonNullable.FieldForEncapsulatedValue.Content, Extensions.HasFieldForEncapsulatedValue),
                new(Expected.NonNullable.InequalityOperatorForValue.Content, Extensions.HasInequalityOperatorForValue),
            ],
            nameof(NonNullable),
            Maximum: LanguageVersion.CSharp7_3);

        public static readonly Snippets Nullable = new(
            [Generic, NonGeneric],
            Declarations.Main,
            [
                Expected.Nullable.BinaryAdditionOperator,
                Expected.Nullable.BinaryBitwiseAndOperator,
                Expected.Nullable.BinaryBitwiseOrOperator,
                Expected.Nullable.BinaryDivisionOperator,
                Expected.Nullable.BinaryExclusiveOrOperator,
                Expected.Nullable.BinaryGreaterThanOperator,
                Expected.Nullable.BinaryGreaterThanOrEqualOperator,
                Expected.Nullable.BinaryLeftShiftOperator,
                Expected.Nullable.BinaryLessThanOperator,
                Expected.Nullable.BinaryLessThanOrEqualOperator,
                Expected.Nullable.BinaryModulusOperator,
                Expected.Nullable.BinaryMultiplyOperator,
                Expected.Nullable.BinaryRightShiftOperator,
                Expected.Nullable.BinarySubtractionOperator,
                Expected.Nullable.ConstructorForEncapsulatedValue,
                Expected.Nullable.ConversionFromValue,
                Expected.Nullable.ConversionToValue,
                Expected.Nullable.EqualityOperatorForValue,
                Expected.Nullable.EquatableForValue,
                Expected.Nullable.EquatableToValue,
                Expected.Nullable.FieldForEncapsulatedValue,
                Expected.Nullable.ComparableInterface,
                Expected.Nullable.ComparableGenericInterface,
                Expected.Nullable.InequalityOperatorForValue,
                Expected.Nullable.CompareToInt,
                Expected.Nullable.CompareToObject,
                Expected.Nullable.UnaryDecrementOperator,
                Expected.Nullable.UnaryIncrementOperator,
                Expected.Nullable.UnaryOnesComplementOperator,
                Expected.Nullable.UnaryNegationOperator,
                Expected.Nullable.UnaryPlusOperator,
            ],
            [
                new(Expected.Nullable.ConstructorForEncapsulatedValue.Content, Extensions.HasConstructorForEncapsulatedValue),
                new(Expected.Nullable.ConversionFromValue.Content, Extensions.HasConversionFrom),
                new(Expected.Nullable.ConversionToValue.Content, Extensions.HasConversionTo),
                new(Expected.Nullable.EqualityOperatorForValue.Content, Extensions.HasEqualityOperatorForValue),
                new(Expected.Nullable.EquatableForValue.Content, Extensions.HasEquatableForValue),
                new(Expected.Nullable.EquatableToValue.Content, Extensions.IsEquatableToValue),
                new(Expected.Nullable.FieldForEncapsulatedValue.Content, Extensions.HasFieldForEncapsulatedValue),
                new(Expected.Nullable.InequalityOperatorForValue.Content, Extensions.HasInequalityOperatorForValue),
            ],
            nameof(Nullable),
            Minimum: LanguageVersion.CSharp8);
    }
}