//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monify.Strategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BinaryOperatorStrategy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BinaryOperatorStrategy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monify.Strategies.BinaryOperatorStrategy.Resources", typeof(BinaryOperatorStrategy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0}.
        /// </summary>
        internal static string BodySource {
            get {
                return ResourceManager.GetString("BodySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2}.
        /// </summary>
        internal static string CombinedSource {
            get {
                return ResourceManager.GetString("CombinedSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}        {2}.
        /// </summary>
        internal static string GuardedBodySource {
            get {
                return ResourceManager.GetString("GuardedBodySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}
        ///{{
        ///    public static {2} operator {3}({4} left, {5} right)
        ///    {{
        ///{6}
        ///    }}
        ///}}.
        /// </summary>
        internal static string GuardedOperatorSource {
            get {
                return ResourceManager.GetString("GuardedOperatorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         if (ReferenceEquals({0}, null))
        ///        {{
        ///            throw new ArgumentNullException(&quot;{1}&quot;);
        ///        }}
        ///.
        /// </summary>
        internal static string GuardSource {
            get {
                return ResourceManager.GetString("GuardSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string OperationSource {
            get {
                return ResourceManager.GetString("OperationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}
        ///{{
        ///    public static {2} operator {3}({4} left, {5} right)
        ///    {{
        ///{6}
        ///    }}
        ///}}.
        /// </summary>
        internal static string OperatorSource {
            get {
                return ResourceManager.GetString("OperatorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return new {0}({1});.
        /// </summary>
        internal static string SubjectResultSource {
            get {
                return ResourceManager.GetString("SubjectResultSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return ({0})({1});.
        /// </summary>
        internal static string ValueResultSource {
            get {
                return ResourceManager.GetString("ValueResultSource", resourceCulture);
            }
        }
    }
}
