//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monify.Strategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EquatableStrategy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquatableStrategy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monify.Strategies.EquatableStrategy.Resources", typeof(EquatableStrategy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} : IEquatable&lt;{2}&gt;
        ///{{
        ///}}.
        /// </summary>
        internal static string ContractSource {
            get {
                return ResourceManager.GetString("ContractSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global::System.Collections.Generic.EqualityComparer&lt;{0}&gt;.Default.Equals({1}, other).
        /// </summary>
        internal static string EqualityComparerSource {
            get {
                return ResourceManager.GetString("EqualityComparerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.IsDefault ? other.IsDefault : !other.IsDefault &amp;&amp; {1}.
        /// </summary>
        internal static string ImmutableArrayEqualitySource {
            get {
                return ResourceManager.GetString("ImmutableArrayEqualitySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}
        ///{{
        ///    public bool Equals({2} other)
        ///    {{
        ///        if (ReferenceEquals(this, other))
        ///        {{
        ///            return true;
        ///        }}
        ///
        ///        if (ReferenceEquals(other, null))
        ///        {{
        ///            return false;
        ///        }}
        ///
        ///        return {3};
        ///    }}
        ///}}.
        /// </summary>
        internal static string ImplementationSource {
            get {
                return ResourceManager.GetString("ImplementationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global::Monify.Internal.SequenceEqualityComparer.Default.Equals({0}, other).
        /// </summary>
        internal static string SequenceEqualitySource {
            get {
                return ResourceManager.GetString("SequenceEqualitySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals(other.{0}).
        /// </summary>
        internal static string SubjectEqualitySource {
            get {
                return ResourceManager.GetString("SubjectEqualitySource", resourceCulture);
            }
        }
    }
}
