//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monify.Strategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonConverterStrategy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonConverterStrategy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monify.Strategies.JsonConverterStrategy.Resources", typeof(JsonConverterStrategy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Text.Json.Serialization.JsonConverter(typeof({4}))]
        ///{0} {1}
        ///{{
        ///    public sealed class Converter : global::System.Text.Json.Serialization.JsonConverter&lt;{1}&gt;
        ///    {{
        ///        public override {1} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        ///        {{
        ///            return new {1}(global::System.Text.Json.JsonSerializer.Deserialize&lt;{2}&gt;(ref reader, options));
        ///        }}
        ///
        ///        public override void Write(global [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConverterSource {
            get {
                return ResourceManager.GetString("ConverterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal sealed class {0} : global::System.Text.Json.Serialization.JsonConverterFactory
        ///{{
        ///    public override bool CanConvert(global::System.Type typeToConvert)
        ///    {{
        ///        return typeToConvert.IsGenericType &amp;&amp; typeToConvert.GetGenericTypeDefinition().FullName == &quot;{1}&quot;;
        ///    }}
        ///
        ///    public override global::System.Text.Json.Serialization.JsonConverter CreateConverter(global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
        ///    {{
        ///        global::System.Type converter = typeToConvert.GetNestedType(&quot;Converter&quot;);
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FactorySource {
            get {
                return ResourceManager.GetString("FactorySource", resourceCulture);
            }
        }
    }
}
