//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monify.Strategies {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MemberPassthroughStrategy_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemberPassthroughStrategy_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monify.Strategies.MemberPassthroughStrategy.Resources", typeof(MemberPassthroughStrategy_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string AccessorDeclarationSource {
            get {
                return ResourceManager.GetString("AccessorDeclarationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string ArgumentSource {
            get {
                return ResourceManager.GetString("ArgumentSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        {0}.
        /// </summary>
        internal static string ConstraintsSource {
            get {
                return ResourceManager.GetString("ConstraintsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.{2}.
        /// </summary>
        internal static string ExplicitMethodPrefixSource {
            get {
                return ResourceManager.GetString("ExplicitMethodPrefixSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.{2}.
        /// </summary>
        internal static string ExplicitPropertyDeclarationSource {
            get {
                return ResourceManager.GetString("ExplicitPropertyDeclarationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (({0}){1}).
        /// </summary>
        internal static string ExplicitTargetSource {
            get {
                return ResourceManager.GetString("ExplicitTargetSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0}
        ///        {{
        ///            return {1};
        ///        }}.
        /// </summary>
        internal static string GetterSource {
            get {
                return ResourceManager.GetString("GetterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[{1}].
        /// </summary>
        internal static string IndexerAccessSource {
            get {
                return ResourceManager.GetString("IndexerAccessSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this[{0}].
        /// </summary>
        internal static string IndexerDeclarationSource {
            get {
                return ResourceManager.GetString("IndexerDeclarationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}{2}({3}).
        /// </summary>
        internal static string MethodCallSource {
            get {
                return ResourceManager.GetString("MethodCallSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}({2}){3}.
        /// </summary>
        internal static string MethodDeclarationSource {
            get {
                return ResourceManager.GetString("MethodDeclarationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string MethodPrefixSource {
            get {
                return ResourceManager.GetString("MethodPrefixSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}
        ///{{
        ///    {2}
        ///    {{
        ///{3}
        ///    }}
        ///}}.
        /// </summary>
        internal static string MethodSource {
            get {
                return ResourceManager.GetString("MethodSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if ({0} is {1})
        ///{{
        ///    {2} = (({3}){4}).{5};
        ///}}.
        /// </summary>
        internal static string ObjectParameterConversionSource {
            get {
                return ResourceManager.GetString("ObjectParameterConversionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} .
        /// </summary>
        internal static string ParameterModifierSource {
            get {
                return ResourceManager.GetString("ParameterModifierSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} {2}.
        /// </summary>
        internal static string ParameterSource {
            get {
                return ResourceManager.GetString("ParameterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.
        /// </summary>
        internal static string PropertyAccessSource {
            get {
                return ResourceManager.GetString("PropertyAccessSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string PropertyDeclarationSource {
            get {
                return ResourceManager.GetString("PropertyDeclarationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}
        ///{{
        ///    {2}
        ///    {{
        ///{3}
        ///    }}
        ///}}.
        /// </summary>
        internal static string PropertySource {
            get {
                return ResourceManager.GetString("PropertySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return {0};.
        /// </summary>
        internal static string ReturnMethodBodySource {
            get {
                return ResourceManager.GetString("ReturnMethodBodySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0}
        ///        {{
        ///            {1} = value;
        ///        }}.
        /// </summary>
        internal static string SetterSource {
            get {
                return ResourceManager.GetString("SetterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;.
        /// </summary>
        internal static string TypeParametersSource {
            get {
                return ResourceManager.GetString("TypeParametersSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0};.
        /// </summary>
        internal static string VoidMethodBodySource {
            get {
                return ResourceManager.GetString("VoidMethodBodySource", resourceCulture);
            }
        }
    }
}
