// <auto-generated/>
namespace Monify.Strategies
{
    using System.Resources;

    [global::System.CodeDom.Compiler.GeneratedCode("ResourceTransform", "1.0.0")]
    internal static class UnaryOperatorStrategy_Resources
    {
        private static readonly ResourceManager _resourceManager = new ResourceManager("Monify.Strategies.UnaryOperatorStrategy.Resources", typeof(UnaryOperatorStrategy_Resources).Assembly);

        internal static string ApplyOperatorNotSupported
        {
            get
            {
                return _resourceManager.GetString(nameof(ApplyOperatorNotSupported), null);
            }
        }

        internal static string FalseOperationSource
        {
            get
            {
                return _resourceManager.GetString(nameof(FalseOperationSource), null);
            }
        }

        internal static string OperationSource
        {
            get
            {
                return _resourceManager.GetString(nameof(OperationSource), null);
            }
        }

        internal static string OperatorSource
        {
            get
            {
                return _resourceManager.GetString(nameof(OperatorSource), null);
            }
        }

        internal static string SubjectResultSource
        {
            get
            {
                return _resourceManager.GetString(nameof(SubjectResultSource), null);
            }
        }

        internal static string TrueOperationSource
        {
            get
            {
                return _resourceManager.GetString(nameof(TrueOperationSource), null);
            }
        }

        internal static string ValueCopyOperatorSource
        {
            get
            {
                return _resourceManager.GetString(nameof(ValueCopyOperatorSource), null);
            }
        }

        internal static string ValueResultSource
        {
            get
            {
                return _resourceManager.GetString(nameof(ValueResultSource), null);
            }
        }
    }
}