// <auto-generated/>
namespace Monify.Semantics
{
    using System.Resources;

    [global::System.CodeDom.Compiler.GeneratedCode("ResourceTransform", "1.0.0")]
    internal static class INamedTypeSymbolExtensions_Resources
    {
        private static readonly ResourceManager _resourceManager = new ResourceManager("Monify.Semantics.INamedTypeSymbolExtensions.Resources", typeof(INamedTypeSymbolExtensions_Resources).Assembly);

        internal static string TypeParameterConstraintSource
        {
            get
            {
                return _resourceManager.GetString(nameof(TypeParameterConstraintSource), null);
            }
        }
    }
}